//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace NuGetUpdate.Installer.ScriptEngine {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class Script {
        
        private ScriptSetup setupField;
        
        private ScriptInstall installField;
        
        private ScriptUpdate updateField;
        
        private ScriptSilentUpdate silentUpdateField;
        
        private ScriptUninstall uninstallField;
        
        /// <remarks/>
        public ScriptSetup Setup {
            get {
                return this.setupField;
            }
            set {
                this.setupField = value;
            }
        }
        
        /// <remarks/>
        public ScriptInstall Install {
            get {
                return this.installField;
            }
            set {
                this.installField = value;
            }
        }
        
        /// <remarks/>
        public ScriptUpdate Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
        
        /// <remarks/>
        public ScriptSilentUpdate SilentUpdate {
            get {
                return this.silentUpdateField;
            }
            set {
                this.silentUpdateField = value;
            }
        }
        
        /// <remarks/>
        public ScriptUninstall Uninstall {
            get {
                return this.uninstallField;
            }
            set {
                this.uninstallField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public partial class ScriptSetup : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public partial class ContainerType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assign", typeof(Assign))]
        [System.Xml.Serialization.XmlElementAttribute("Call", typeof(Call))]
        [System.Xml.Serialization.XmlElementAttribute("Control.CheckBox", typeof(ControlCheckBox))]
        [System.Xml.Serialization.XmlElementAttribute("Control.Label", typeof(ControlLabel))]
        [System.Xml.Serialization.XmlElementAttribute("Control.Link", typeof(ControlLink))]
        [System.Xml.Serialization.XmlElementAttribute("CreateDirectory", typeof(CreateDirectory))]
        [System.Xml.Serialization.XmlElementAttribute("CreateShortcut", typeof(CreateShortcut))]
        [System.Xml.Serialization.XmlElementAttribute("ExecShell", typeof(ExecShell))]
        [System.Xml.Serialization.XmlElementAttribute("ExecWait", typeof(ExecWait))]
        [System.Xml.Serialization.XmlElementAttribute("Function", typeof(Function))]
        [System.Xml.Serialization.XmlElementAttribute("If", typeof(If))]
        [System.Xml.Serialization.XmlElementAttribute("InstallPackage", typeof(InstallPackage))]
        [System.Xml.Serialization.XmlElementAttribute("Message", typeof(Message))]
        [System.Xml.Serialization.XmlElementAttribute("MessageBox", typeof(MessageBox))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Install.DestinationFolder", typeof(PageInstallDestinationFolder))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Install.Finish", typeof(PageInstallFinish))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Install.License", typeof(PageInstallLicense))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Install.Progress", typeof(PageInstallProgress))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Install.StartMenu", typeof(PageInstallStartMenu))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Install.Welcome", typeof(PageInstallWelcome))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Uninstall.Finish", typeof(PageUninstallFinish))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Uninstall.Progress", typeof(PageUninstallProgress))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Uninstall.Welcome", typeof(PageUninstallWelcome))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Update.Finish", typeof(PageUpdateFinish))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Update.Progress", typeof(PageUpdateProgress))]
        [System.Xml.Serialization.XmlElementAttribute("Page.Update.Welcome", typeof(PageUpdateWelcome))]
        [System.Xml.Serialization.XmlElementAttribute("UninstallPackage", typeof(UninstallPackage))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class Assign {
        
        private string variableField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class Call {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Control.CheckBox", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class ControlCheckBox : ContainerType {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Control.Label", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class ControlLabel {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Control.Link", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class ControlLink : ContainerType {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class CreateDirectory {
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class CreateShortcut {
        
        private string shortcutFileNameField;
        
        private string targetFileNameField;
        
        private string iconFileNameField;
        
        private string iconIndexField;
        
        private string startOptionsField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortcutFileName {
            get {
                return this.shortcutFileNameField;
            }
            set {
                this.shortcutFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFileName {
            get {
                return this.targetFileNameField;
            }
            set {
                this.targetFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IconFileName {
            get {
                return this.iconFileNameField;
            }
            set {
                this.iconFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IconIndex {
            get {
                return this.iconIndexField;
            }
            set {
                this.iconIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartOptions {
            get {
                return this.startOptionsField;
            }
            set {
                this.startOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class ExecShell {
        
        private string verbField;
        
        private string fileNameField;
        
        private string argumentsField;
        
        private ProcessWindowStyle windowStyleField;
        
        public ExecShell() {
            this.windowStyleField = ProcessWindowStyle.Normal;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Verb {
            get {
                return this.verbField;
            }
            set {
                this.verbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ProcessWindowStyle.Normal)]
        public ProcessWindowStyle WindowStyle {
            get {
                return this.windowStyleField;
            }
            set {
                this.windowStyleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public enum ProcessWindowStyle {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Hidden,
        
        /// <remarks/>
        Minimized,
        
        /// <remarks/>
        Maximized,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class ExecWait {
        
        private string fileNameField;
        
        private string argumentsField;
        
        private ProcessWindowStyle windowStyleField;
        
        public ExecWait() {
            this.windowStyleField = ProcessWindowStyle.Normal;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ProcessWindowStyle.Normal)]
        public ProcessWindowStyle WindowStyle {
            get {
                return this.windowStyleField;
            }
            set {
                this.windowStyleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class Function : ContainerType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class If {
        
        private IfThen thenField;
        
        private IfElse elseField;
        
        private string conditionField;
        
        /// <remarks/>
        public IfThen Then {
            get {
                return this.thenField;
            }
            set {
                this.thenField = value;
            }
        }
        
        /// <remarks/>
        public IfElse Else {
            get {
                return this.elseField;
            }
            set {
                this.elseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public partial class IfThen : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public partial class IfElse : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class InstallPackage {
        
        private bool overwriteField;
        
        private bool intoRootField;
        
        public InstallPackage() {
            this.overwriteField = true;
            this.intoRootField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IntoRoot {
            get {
                return this.intoRootField;
            }
            set {
                this.intoRootField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class Message {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class MessageBox {
        
        private string textField;
        
        private MessageBoxButtons buttonsField;
        
        private MessageBoxIcon iconField;
        
        private string resultField;
        
        private string valueField;
        
        public MessageBox() {
            this.buttonsField = MessageBoxButtons.OK;
            this.iconField = MessageBoxIcon.None;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(MessageBoxButtons.OK)]
        public MessageBoxButtons Buttons {
            get {
                return this.buttonsField;
            }
            set {
                this.buttonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(MessageBoxIcon.None)]
        public MessageBoxIcon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public enum MessageBoxButtons {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        OKCancel,
        
        /// <remarks/>
        AbortRetryIgnore,
        
        /// <remarks/>
        YesNoCancel,
        
        /// <remarks/>
        YesNo,
        
        /// <remarks/>
        RetryCancel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public enum MessageBoxIcon {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Hand,
        
        /// <remarks/>
        Question,
        
        /// <remarks/>
        Exclamation,
        
        /// <remarks/>
        Asterisk,
        
        /// <remarks/>
        Stop,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Information,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Install.DestinationFolder", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageInstallDestinationFolder {
        
        private bool enabledField;
        
        private bool isLastField;
        
        public PageInstallDestinationFolder() {
            this.enabledField = true;
            this.isLastField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsLast {
            get {
                return this.isLastField;
            }
            set {
                this.isLastField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Install.Finish", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageInstallFinish : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Install.License", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageInstallLicense {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Install.Progress", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageInstallProgress : ContainerType {
        
        private bool progressVisibleField;
        
        public PageInstallProgress() {
            this.progressVisibleField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ProgressVisible {
            get {
                return this.progressVisibleField;
            }
            set {
                this.progressVisibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Install.StartMenu", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageInstallStartMenu {
        
        private bool enabledField;
        
        private bool createStartMenuVisibleField;
        
        private bool createOnDesktopVisibleField;
        
        private bool isLastField;
        
        public PageInstallStartMenu() {
            this.enabledField = true;
            this.createStartMenuVisibleField = true;
            this.createOnDesktopVisibleField = false;
            this.isLastField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool CreateStartMenuVisible {
            get {
                return this.createStartMenuVisibleField;
            }
            set {
                this.createStartMenuVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CreateOnDesktopVisible {
            get {
                return this.createOnDesktopVisibleField;
            }
            set {
                this.createOnDesktopVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsLast {
            get {
                return this.isLastField;
            }
            set {
                this.isLastField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Install.Welcome", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageInstallWelcome {
        
        private bool isLastField;
        
        public PageInstallWelcome() {
            this.isLastField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsLast {
            get {
                return this.isLastField;
            }
            set {
                this.isLastField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Uninstall.Finish", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageUninstallFinish : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Uninstall.Progress", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageUninstallProgress : ContainerType {
        
        private bool progressVisibleField;
        
        public PageUninstallProgress() {
            this.progressVisibleField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ProgressVisible {
            get {
                return this.progressVisibleField;
            }
            set {
                this.progressVisibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Uninstall.Welcome", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageUninstallWelcome {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Update.Finish", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageUpdateFinish : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Update.Progress", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageUpdateProgress : ContainerType {
        
        private bool progressVisibleField;
        
        public PageUpdateProgress() {
            this.progressVisibleField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ProgressVisible {
            get {
                return this.progressVisibleField;
            }
            set {
                this.progressVisibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Page.Update.Welcome", Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class PageUpdateWelcome {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1", IsNullable=false)]
    public partial class UninstallPackage {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public partial class ScriptInstall : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public partial class ScriptUpdate : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public partial class ScriptSilentUpdate : ContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/pvginkel/NuGetUpdate/Script/v1")]
    public partial class ScriptUninstall : ContainerType {
    }
}
