//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetUpdate.Installer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UILabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGetUpdate.Installer.UILabels", typeof(UILabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current context does not allow action {0}.
        /// </summary>
        internal static string ActionNotAllow {
            get {
                return ResourceManager.GetString("ActionNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is still running. Close the application and retry..
        /// </summary>
        internal static string ApplicationStillRunning {
            get {
                return ResourceManager.GetString("ApplicationStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit {0}?.
        /// </summary>
        internal static string AreYouSureQuit {
            get {
                return ResourceManager.GetString("AreYouSureQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find script.
        /// </summary>
        internal static string CannotFindScript {
            get {
                return ResourceManager.GetString("CannotFindScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove existing installation folder.
        /// </summary>
        internal static string CannotRemoveBinFolder {
            get {
                return ResourceManager.GetString("CannotRemoveBinFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A continuation is already running.
        /// </summary>
        internal static string ContinuationAlreadyRunning {
            get {
                return ResourceManager.GetString("ContinuationAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current context does not allow controls.
        /// </summary>
        internal static string ControlsNotAllowed {
            get {
                return ResourceManager.GetString("ControlsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}....
        /// </summary>
        internal static string CopyingFile {
            get {
                return ResourceManager.GetString("CopyingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating directory {0}....
        /// </summary>
        internal static string CreatingDirectory {
            get {
                return ResourceManager.GetString("CreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating shortcut {0}....
        /// </summary>
        internal static string CreatingShortcut {
            get {
                return ResourceManager.GetString("CreatingShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory {0}....
        /// </summary>
        internal static string DeletingDirectory {
            get {
                return ResourceManager.GetString("DeletingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}....
        /// </summary>
        internal static string DeletingFile {
            get {
                return ResourceManager.GetString("DeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while downloading the setup:.
        /// </summary>
        internal static string DownloadFailure {
            get {
                return ResourceManager.GetString("DownloadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}....
        /// </summary>
        internal static string ExecutingProcess {
            get {
                return ResourceManager.GetString("ExecutingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function {0} does not exist.
        /// </summary>
        internal static string FunctionNotFound {
            get {
                return ResourceManager.GetString("FunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions cannot be nested.
        /// </summary>
        internal static string FunctionsCannotBeNested {
            get {
                return ResourceManager.GetString("FunctionsCannotBeNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallButtonLabel {
            get {
                return ResourceManager.GetString("InstallButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the {0} Setup Wizard.
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been installed on your computer..
        /// </summary>
        internal static string InstallCompleteSubText {
            get {
                return ResourceManager.GetString("InstallCompleteSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Install to start the installation..
        /// </summary>
        internal static string InstallContinue {
            get {
                return ResourceManager.GetString("InstallContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {0} is being installed..
        /// </summary>
        internal static string InstallingSubText {
            get {
                return ResourceManager.GetString("InstallingSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0} Setup Wizard.
        /// </summary>
        internal static string InstallWelcome {
            get {
                return ResourceManager.GetString("InstallWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through the installation of {0}..
        /// </summary>
        internal static string InstallWelcomeSubText {
            get {
                return ResourceManager.GetString("InstallWelcomeSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded package is invalid.
        /// </summary>
        internal static string InvalidPackage {
            get {
                return ResourceManager.GetString("InvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script is invalid.
        /// </summary>
        internal static string InvalidScript {
            get {
                return ResourceManager.GetString("InvalidScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetPath root is invalid.
        /// </summary>
        internal static string InvalidTargetPathRoot {
            get {
                return ResourceManager.GetString("InvalidTargetPathRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string NextButtonLabel {
            get {
                return ResourceManager.GetString("NextButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to continue..
        /// </summary>
        internal static string NextContinue {
            get {
                return ResourceManager.GetString("NextContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Setup.
        /// </summary>
        internal static string NuGetSetup {
            get {
                return ResourceManager.GetString("NuGetSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0} is not installed on this computer.
        /// </summary>
        internal static string PackageNotInstalled {
            get {
                return ResourceManager.GetString("PackageNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page is not a control host.
        /// </summary>
        internal static string PageNotControlHost {
            get {
                return ResourceManager.GetString("PageNotControlHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page is not waitable.
        /// </summary>
        internal static string PageNotWaitable {
            get {
                return ResourceManager.GetString("PageNotWaitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages cannot be nested.
        /// </summary>
        internal static string PagesCannotBeNested {
            get {
                return ResourceManager.GetString("PagesCannotBeNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress page is required.
        /// </summary>
        internal static string ProgressPageIsRequired {
            get {
                return ResourceManager.GetString("ProgressPageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0} (retrying)....
        /// </summary>
        internal static string RetryingDeleteFile {
            get {
                return ResourceManager.GetString("RetryingDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory {0} (retrying)....
        /// </summary>
        internal static string RetryingDeletingDirectory {
            get {
                return ResourceManager.GetString("RetryingDeletingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script variable &apos;{0}&apos; was expected but not set.
        /// </summary>
        internal static string ScriptVariableNotFound {
            get {
                return ResourceManager.GetString("ScriptVariableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update should not be restarted.
        /// </summary>
        internal static string ShouldNotRestart {
            get {
                return ResourceManager.GetString("ShouldNotRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is required when installing.
        /// </summary>
        internal static string SiteRequiredForInstall {
            get {
                return ResourceManager.GetString("SiteRequiredForInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either -i, -u or -r must be specified..
        /// </summary>
        internal static string SpecifyModeFlag {
            get {
                return ResourceManager.GetString("SpecifyModeFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while re-starting the setup:.
        /// </summary>
        internal static string StartSetupFailure {
            get {
                return ResourceManager.GetString("StartSetupFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetPath is not rooted.
        /// </summary>
        internal static string TargetPathNotRooted {
            get {
                return ResourceManager.GetString("TargetPathNotRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required when installing.
        /// </summary>
        internal static string TitleRequiredForInstall {
            get {
                return ResourceManager.GetString("TitleRequiredForInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected failure occured:.
        /// </summary>
        internal static string UnexpectedFailure {
            get {
                return ResourceManager.GetString("UnexpectedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the {0} Uninstallation Wizard.
        /// </summary>
        internal static string UninstallComplete {
            get {
                return ResourceManager.GetString("UninstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed from your computer..
        /// </summary>
        internal static string UninstallCompleteSubText {
            get {
                return ResourceManager.GetString("UninstallCompleteSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {0} is being uninstalled..
        /// </summary>
        internal static string UninstallingSubText {
            get {
                return ResourceManager.GetString("UninstallingSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0} Uninstallation Wizard.
        /// </summary>
        internal static string UninstallWelcome {
            get {
                return ResourceManager.GetString("UninstallWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through the uninstallation of {0}..
        /// </summary>
        internal static string UninstallWelcomeSubText {
            get {
                return ResourceManager.GetString("UninstallWelcomeSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the {0} Update Wizard.
        /// </summary>
        internal static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated to its latest version..
        /// </summary>
        internal static string UpdateCompleteSubText {
            get {
                return ResourceManager.GetString("UpdateCompleteSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0} Update Wizard.
        /// </summary>
        internal static string UpdateWelcome {
            get {
                return ResourceManager.GetString("UpdateWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through the update process of {0}..
        /// </summary>
        internal static string UpdateWelcomeSubText {
            get {
                return ResourceManager.GetString("UpdateWelcomeSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {0} is being updated..
        /// </summary>
        internal static string UpdatingSubText {
            get {
                return ResourceManager.GetString("UpdatingSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSD validation failed for script.
        /// </summary>
        internal static string XsdValidationFailed {
            get {
                return ResourceManager.GetString("XsdValidationFailed", resourceCulture);
            }
        }
    }
}
